# Generated by Django 6.0 on 2025-12-10 10:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=3, unique=True)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("symbol", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1"), max_digits=18
                    ),
                ),
                (
                    "exchange_source",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="core_curren_code_fcefac_idx"),
                    models.Index(fields=["name"], name="core_curren_name_567cfb_idx"),
                    models.Index(
                        fields=["is_active"], name="core_curren_is_acti_ed0dd5_idx"
                    ),
                ],
            },
        ),
    ]
