# Generated by Django 6.0 on 2025-12-11 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Category name. Must be unique per user and type.",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[("Income", "Income"), ("Expense", "Expense")],
                        db_index=True,
                        default="Expense",
                        help_text="Indicates whether this category is for income or expenses.",
                        max_length=20,
                    ),
                ),
                ("is_system_category", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this category is currently active.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional parent category for hierarchical grouping.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="core.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owner of this category. Null indicates a system-wide category.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "indexes": [
                    models.Index(fields=["user", "is_active"], name="idx_user_active"),
                    models.Index(
                        fields=["category_type", "is_active"], name="idx_type_active"
                    ),
                    models.Index(fields=["parent"], name="idx_parent_category"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name", "category_type"),
                        name="uq_category_user_name_type",
                    )
                ],
            },
        ),
    ]
