# Generated by Django 6.0 on 2025-12-15 08:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={
                "ordering": ["code"],
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="uq_category_user_name_type",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="idx_parent_category",
        ),
        migrations.RemoveIndex(
            model_name="currency",
            name="core_curren_is_acti_ed0dd5_idx",
        ),
        migrations.RenameIndex(
            model_name="category",
            new_name="idx_categori_use_is_",
            old_name="idx_user_active",
        ),
        migrations.RenameIndex(
            model_name="category",
            new_name="idx_categori_cat_is_",
            old_name="idx_type_active",
        ),
        migrations.RenameIndex(
            model_name="currency",
            new_name="currencies_code_c454c7_idx",
            old_name="core_curren_code_fcefac_idx",
        ),
        migrations.RenameIndex(
            model_name="currency",
            new_name="currencies_name_104300_idx",
            old_name="core_curren_name_567cfb_idx",
        ),
        migrations.AddField(
            model_name="category",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True, help_text="When this category was last used", null=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="transaction_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of transactions using this category"
            ),
        ),
        migrations.AddField(
            model_name="currency",
            name="decimal_places",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Number of decimal places for this currency",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AddField(
            model_name="currency",
            name="exchange_updated_at",
            field=models.DateTimeField(
                blank=True, help_text="When exchange rate was last updated", null=True
            ),
        ),
        migrations.AddField(
            model_name="currency",
            name="historical_rates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Historical exchange rates with timestamps",
            ),
        ),
        migrations.AddField(
            model_name="currency",
            name="is_base_currency",
            field=models.BooleanField(
                default=False, help_text="Whether this is the system's base currency"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[("Income", "Income"), ("Expense", "Expense")],
                db_index=True,
                default="Expense",
                help_text="Type of transactions this category is for",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed description of the category", null=True
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this category is active for use",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_system_category",
            field=models.BooleanField(
                default=False, help_text="Whether this is a system-created category"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Category name (must be unique per user and type)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent category for hierarchical organization.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="core.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of this category. Null for system categories.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="ISO 4217 currency code (e.g., USD, EUR)",
                max_length=3,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="currency",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("1.0"),
                help_text="Exchange rate to base currency",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="exchange_source",
            field=models.CharField(
                blank=True,
                help_text="Source of exchange rate (e.g., 'ECB', 'OpenExchangeRates')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this currency is active for use",
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Full currency name (e.g., US Dollar)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="symbol",
            field=models.CharField(
                blank=True,
                help_text="Currency symbol (e.g., $, €)",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "is_active"], name="idx_categori_par_is_"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["user", "category_type", "is_active"],
                name="idx_categori_use_cat_is_",
            ),
        ),
        migrations.AddIndex(
            model_name="currency",
            index=models.Index(
                fields=["is_active", "code"], name="currencies_is_acti_fb59a1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("user", "name", "category_type"),
                name="idx_categori_use_nam_cat",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="idx_categori_par_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="currency",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)),
                name="currency_exchange_rate_positive",
            ),
        ),
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
        migrations.AlterModelTable(
            name="currency",
            table="currencies",
        ),
    ]
