# Generated by Django 6.0 on 2025-12-16 13:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_currency_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="decimal_places",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Number of decimal places for this currency",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=10,
                default=Decimal("1.0"),
                help_text="Exchange rate to base currency",
                max_digits=20,
            ),
        ),
    ]
