# Generated by Django 6.0 on 2025-12-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/%Y/%m/%d/"
            ),
        ),
    ]
