# Generated by Django 6.0 on 2025-12-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0002_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="annual_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="currency_preference",
            field=models.CharField(blank=True, default="USD", max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="emergency_fund_target",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="financial_advisor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="financial_goals",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="investment_experience",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="monthly_income_target",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="notification_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="privacy_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="retirement_goal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="risk_tolerance",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="premium_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
