# Generated by Django 6.0 on 2025-12-17 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("auths", "0003_profile_annual_income_profile_currency_preference_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="passcode",
            name="unique_active_passcode_per_user_per_type",
        ),
        migrations.RemoveConstraint(
            model_name="profile",
            name="unique_profile_per_user",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="dob",
            new_name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_activity",
        ),
        migrations.AddField(
            model_name="user",
            name="last_activity_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="passcode",
            name="code",
            field=models.CharField(help_text="One-time passcode value", max_length=15),
        ),
        migrations.AlterField(
            model_name="passcode",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="passcode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passcodes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="notification_preferences",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="privacy_settings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="Primary identifier used for authentication",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True,
                help_text="Public-facing identifier (non-auth)",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="passcode",
            index=models.Index(fields=["code"], name="passcodes_code_38df54_idx"),
        ),
        migrations.AddIndex(
            model_name="passcode",
            index=models.Index(
                fields=["expires_at"], name="passcodes_expires_c00086_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active"], name="users_is_acti_847b48_idx"),
        ),
        migrations.AddConstraint(
            model_name="passcode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_used", False)),
                fields=("user", "code_type"),
                name="unique_active_passcode_per_user_and_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="passcode",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("created_at"))),
                name="expires_after_creation",
            ),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="emergency_fund_target",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="financial_advisor",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="financial_goals",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="investment_experience",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="monthly_income_target",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="retirement_goal",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="risk_tolerance",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="street",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="zip_code",
        ),
    ]
