# Generated by Django 6.0 on 2025-12-18 12:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auths",
            "0004_remove_passcode_unique_active_passcode_per_user_per_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device", models.CharField(default="Unknown Device", max_length=255)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_activity",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Session",
                "verbose_name_plural": "Device Sessions",
                "db_table": "device_sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "ip_address"],
                        name="device_sess_user_id_3a9e33_idx",
                    ),
                    models.Index(
                        fields=["last_activity"], name="device_sess_last_ac_223720_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserLoginAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device", models.CharField(default="Unknown Device", max_length=255)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure")],
                        default="success",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Login Audit",
                "verbose_name_plural": "User Login Audits",
                "db_table": "login_audits",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="login_audit_user_id_7fe073_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="login_audit_timesta_ec4e39_idx"
                    ),
                ],
            },
        ),
    ]
