# Generated by Django 6.0 on 2025-12-18 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0005_devicesession_userloginaudit"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userloginaudit",
            new_name="user_login__user_id_9f83f5_idx",
            old_name="login_audit_user_id_7fe073_idx",
        ),
        migrations.RenameIndex(
            model_name="userloginaudit",
            new_name="user_login__timesta_e34d07_idx",
            old_name="login_audit_timesta_ec4e39_idx",
        ),
        migrations.AlterField(
            model_name="userloginaudit",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("failure", "Failure")],
                db_index=True,
                default="success",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userloginaudit",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterModelTable(
            name="userloginaudit",
            table="user_login_audits",
        ),
    ]
