# Generated by Django 6.0 on 2025-12-18 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auths",
            "0006_rename_login_audit_user_id_7fe073_idx_user_login__user_id_9f83f5_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userloginaudit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for unauthenticated or unknown-user login attempts",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="login_audits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
