# Generated by Django 6.0 on 2025-12-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0007_alter_userloginaudit_user"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userloginaudit",
            name="user_login__timesta_e34d07_idx",
        ),
        migrations.AddField(
            model_name="userloginaudit",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="Email used during login attempt (even if user not found)",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="userloginaudit",
            index=models.Index(
                fields=["email", "status"], name="user_login__email_5ded8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userloginaudit",
            index=models.Index(
                fields=["ip_address", "timestamp"],
                name="user_login__ip_addr_203f35_idx",
            ),
        ),
    ]
