# Generated by Django 6.0 on 2025-12-22 08:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0008_remove_userloginaudit_user_login__timesta_e34d07_idx_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("annual_income__gte", Decimal("0.00")),
                    ("annual_income__isnull", True),
                    _connector="OR",
                ),
                name="annual_income_non_negative",
            ),
        ),
    ]
