# Generated by Django 6.0 on 2025-12-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0009_profile_annual_income_non_negative"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userloginaudit",
            name="status",
            field=models.CharField(
                choices=[("Success", "Success"), ("Failure", "Failure")],
                db_index=True,
                default="Success",
                max_length=10,
            ),
        ),
    ]
