# Generated by Django 6.0 on 2025-12-10 12:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the account (e.g., 'Main Checking')",
                        max_length=255,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Checking", "Checking"),
                            ("Savings", "Savings"),
                            ("Credit Card", "Credit Card"),
                            ("Cash", "Cash"),
                            ("Investment", "Investment"),
                            ("Loan", "Loan"),
                            ("Other", "Other"),
                        ],
                        default="Cash",
                        max_length=50,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Bank account number or identifier",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the bank or institution",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current calculated balance including all transactions",
                        max_digits=18,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the user's primary account",
                    ),
                ),
                (
                    "institution_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Store generic data for bank integrations",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="core.currency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "db_table": "accounts",
                "ordering": ["-is_primary", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "account_type"],
                        name="accounts_user_id_298889_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"), name="unique_account_name_per_user"
                    )
                ],
            },
        ),
    ]
