# Generated by Django 6.0 on 2025-12-11 13:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0002_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Transaction title or name",
                        max_length=255,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("Income", "Income"), ("Expense", "Expense")],
                        db_index=True,
                        help_text="Income or Expense",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount in account currency",
                        max_digits=18,
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original amount before currency conversion",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "original_currency",
                    models.CharField(
                        blank=True,
                        help_text="Original currency before conversion",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.0"),
                        help_text="Exchange rate from original currency to account currency",
                        max_digits=18,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        db_index=True,
                        default="USD",
                        help_text="Currency of the transaction",
                        max_length=3,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Pending", "Pending"),
                            ("Canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="Completed",
                        max_length=50,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("is_recurring", models.BooleanField(default=False)),
                ("is_transfer", models.BooleanField(default=False)),
                (
                    "transaction_date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account associated with the transaction, optional",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="accounts.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category of the transaction",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="core.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of the transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "transaction_date"],
                        name="accounts_tr_user_id_7b2efb_idx",
                    ),
                    models.Index(
                        fields=["account", "transaction_date"],
                        name="accounts_tr_account_3b8440_idx",
                    ),
                    models.Index(
                        fields=["category", "transaction_type"],
                        name="accounts_tr_categor_64aac5_idx",
                    ),
                    models.Index(
                        fields=["status"], name="accounts_tr_status_9c451f_idx"
                    ),
                ],
            },
        ),
    ]
