# Generated by Django 6.0 on 2025-12-12 14:44

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_transaction"),
        ("core", "0002_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("Pending", "Pending"),
                    ("Canceled", "Canceled"),
                ],
                db_index=True,
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Name of the budget (e.g., "Monthly Groceries")',
                        max_length=255,
                    ),
                ),
                (
                    "budget_type",
                    models.CharField(
                        choices=[
                            ("category", "Category Budget"),
                            ("overall", "Overall Budget"),
                            ("goal", "Goal-based Budget"),
                        ],
                        db_index=True,
                        default="category",
                        help_text="Type of budget",
                        max_length=20,
                    ),
                ),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total budgeted amount",
                        max_digits=18,
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount spent in budget period",
                        max_digits=18,
                    ),
                ),
                (
                    "total_remaining",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Remaining budget amount",
                        max_digits=18,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom Period"),
                        ],
                        default="monthly",
                        help_text="Budget period type",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Start date of the budget period"),
                ),
                (
                    "end_date",
                    models.DateField(help_text="End date of the budget period"),
                ),
                (
                    "rollover_unused",
                    models.BooleanField(
                        default=False,
                        help_text="Roll over unused amount to next period",
                    ),
                ),
                (
                    "rollover_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount rolled over from previous period",
                        max_digits=18,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this budget is active",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the budget",
                        null=True,
                    ),
                ),
                (
                    "notification_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("80.00"),
                        help_text="Percentage threshold for notifications (e.g., 80 for 80%)",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_recalculated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When spending was last recalculated",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific category for category budgets",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="core.category",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="Currency for this budget",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets",
                        to="core.currency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this budget",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "db_table": "budgets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BudgetCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount allocated to this category",
                        max_digits=18,
                    ),
                ),
                (
                    "spent_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount spent in this category",
                        max_digits=18,
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Remaining amount for this category",
                        max_digits=18,
                    ),
                ),
                (
                    "percentage_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of allocation used (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_categories",
                        to="accounts.budget",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_categories",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Category",
                "verbose_name_plural": "Budget Categories",
                "db_table": "budget_categories",
            },
        ),
        migrations.CreateModel(
            name="FinancialGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the financial goal", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the goal",
                        null=True,
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings Goal"),
                            ("debt", "Debt Repayment"),
                            ("investment", "Investment Goal"),
                            ("purchase", "Major Purchase"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="savings",
                        help_text="Type of financial goal",
                        max_length=50,
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target amount to achieve",
                        max_digits=18,
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current amount saved/paid",
                        max_digits=18,
                    ),
                ),
                (
                    "monthly_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Planned monthly contribution",
                        max_digits=18,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="When the goal tracking started",
                    ),
                ),
                ("target_date", models.DateField(help_text="Target completion date")),
                (
                    "achieved_date",
                    models.DateField(
                        blank=True, help_text="Date when goal was achieved", null=True
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High Priority"),
                            ("medium", "Medium Priority"),
                            ("low", "Low Priority"),
                        ],
                        db_index=True,
                        default="medium",
                        help_text="Priority level of the goal",
                        max_length=10,
                    ),
                ),
                (
                    "is_achieved",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the goal has been achieved",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this goal is actively being tracked",
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage progress toward goal (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "months_remaining",
                    models.IntegerField(
                        default=0,
                        help_text="Estimated months remaining at current rate",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="Currency for this goal",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_goals",
                        to="core.currency",
                    ),
                ),
                (
                    "linked_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account linked to this goal (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_goals",
                        to="accounts.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this goal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Goal",
                "verbose_name_plural": "Financial Goals",
                "db_table": "financial_goals",
                "ordering": ["priority", "-target_date"],
            },
        ),
        migrations.CreateModel(
            name="RecurringTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the recurring transaction", max_length=255
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("Income", "Income"), ("Expense", "Expense")],
                        db_index=True,
                        help_text="Type of transaction (income or expense)",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount for each occurrence",
                        max_digits=18,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        db_index=True,
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Short description",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or details", null=True
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("bi_weekly", "Bi-Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        help_text="How often the transaction repeats",
                        max_length=20,
                    ),
                ),
                (
                    "interval",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Every N periods (e.g., 2 for every 2 weeks)",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Day of month for monthly transactions (1-31)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ],
                        help_text="Day of week for weekly transactions",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date when recurring transactions should start",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional end date for the recurring transaction",
                        null=True,
                    ),
                ),
                (
                    "next_occurrence",
                    models.DateField(
                        db_index=True,
                        help_text="Next date when transaction should be generated",
                    ),
                ),
                (
                    "occurrences_created",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of transactions already generated"
                    ),
                ),
                (
                    "max_occurrences",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of occurrences (optional)",
                        null=True,
                    ),
                ),
                (
                    "is_transfer",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a transfer between accounts",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this recurring transaction is active",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Tags for categorization"
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Attachment metadata (paths, descriptions)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the last transaction was generated",
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account to use for generated transactions (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_transactions",
                        to="accounts.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category for generated transactions",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_transactions",
                        to="core.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this recurring transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring Transaction",
                "verbose_name_plural": "Recurring Transactions",
                "db_table": "recurring_transactions",
                "ordering": ["next_occurrence", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_name",
                    models.CharField(help_text="Name of the report", max_length=255),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("spending_by_category", "Spending by Category"),
                            ("income_vs_expense", "Income vs Expense"),
                            ("net_worth", "Net Worth"),
                            ("budget_vs_actual", "Budget vs Actual"),
                            ("cash_flow", "Cash Flow"),
                            ("custom", "Custom Report"),
                        ],
                        db_index=True,
                        help_text="Type of report",
                        max_length=50,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="Start date of report period"),
                ),
                ("period_end", models.DateField(help_text="End date of report period")),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuration parameters for the report",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("csv", "CSV"),
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("html", "HTML"),
                        ],
                        default="json",
                        help_text="Output format of the report",
                        max_length=10,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        help_text="Generated report data (for JSON format)",
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Generated report file",
                        max_length=500,
                        null=True,
                        upload_to="reports/%Y/%m/%d/",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Size of the generated file in bytes",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of report generation",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if generation failed",
                        null=True,
                    ),
                ),
                (
                    "generation_duration",
                    models.FloatField(
                        blank=True,
                        help_text="Time taken to generate report (seconds)",
                        null=True,
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 checksum of report data/file",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this report should be automatically deleted",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, help_text="When the report was generated", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who requested this report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "db_table": "reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["user", "is_active"], name="budgets_user_id_ce81fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["user", "budget_type"], name="budgets_user_id_99b014_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["start_date", "end_date"], name="budgets_start_d_6720b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["category", "is_active"], name="budgets_categor_04e6f2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_budget__gt", 0)),
                name="budget_total_budget_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="budget_end_date_after_start_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user", "name"),
                name="unique_active_budget_name_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="budgetcategory",
            index=models.Index(
                fields=["budget", "category"], name="budget_cate_budget__5aa1b4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("allocated_amount__gt", 0)),
                name="budget_category_allocated_amount_positive",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budgetcategory",
            unique_together={("budget", "category")},
        ),
        migrations.AddIndex(
            model_name="financialgoal",
            index=models.Index(
                fields=["user", "is_active"], name="financial_g_user_id_1bf197_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialgoal",
            index=models.Index(
                fields=["user", "goal_type"], name="financial_g_user_id_58588b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialgoal",
            index=models.Index(
                fields=["target_date"], name="financial_g_target__1af2d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialgoal",
            index=models.Index(
                fields=["priority", "target_date"],
                name="financial_g_priorit_4573ba_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialgoal",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_amount__gt", 0)),
                name="financial_goal_target_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialgoal",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_amount__gte", 0)),
                name="financial_goal_current_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialgoal",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_date__gt", models.F("start_date"))),
                name="financial_goal_target_date_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringtransaction",
            index=models.Index(
                fields=["user", "is_active", "next_occurrence"],
                name="recurring_t_user_id_839084_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringtransaction",
            index=models.Index(
                fields=["user", "frequency"], name="recurring_t_user_id_357b2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recurringtransaction",
            index=models.Index(
                fields=["next_occurrence", "is_active"],
                name="recurring_t_next_oc_55ebbd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="recurring_transaction_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("interval__gte", 1)),
                name="recurring_transaction_interval_minimum",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringtransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gt", models.F("start_date")),
                    _connector="OR",
                ),
                name="recurring_transaction_valid_end_date",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["user", "report_type"], name="reports_user_id_3dda96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["user", "status"], name="reports_user_id_280740_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["expires_at"], name="reports_expires_a8436a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["created_at"], name="reports_created_c5f642_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gt", models.F("period_start"))),
                name="report_period_end_after_start",
            ),
        ),
    ]
