# Generated by Django 6.0 on 2025-12-15 08:55

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_transaction_status_and_more"),
        ("core", "0003_alter_currency_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="recurringtransaction",
            name="recurring_t_user_id_839084_idx",
        ),
        migrations.RemoveIndex(
            model_name="recurringtransaction",
            name="recurring_t_user_id_357b2e_idx",
        ),
        migrations.RemoveIndex(
            model_name="recurringtransaction",
            name="recurring_t_next_oc_55ebbd_idx",
        ),
        migrations.RemoveConstraint(
            model_name="recurringtransaction",
            name="recurring_transaction_amount_positive",
        ),
        migrations.RemoveConstraint(
            model_name="recurringtransaction",
            name="recurring_transaction_interval_minimum",
        ),
        migrations.RemoveConstraint(
            model_name="recurringtransaction",
            name="recurring_transaction_valid_end_date",
        ),
        migrations.RemoveConstraint(
            model_name="account",
            name="unique_account_name_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="budget",
            name="budget_total_budget_positive",
        ),
        migrations.RemoveConstraint(
            model_name="budget",
            name="budget_end_date_after_start_date",
        ),
        migrations.RemoveConstraint(
            model_name="budget",
            name="unique_active_budget_name_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="budgetcategory",
            name="budget_category_allocated_amount_positive",
        ),
        migrations.RemoveConstraint(
            model_name="financialgoal",
            name="financial_goal_target_amount_positive",
        ),
        migrations.RemoveConstraint(
            model_name="financialgoal",
            name="financial_goal_current_amount_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="financialgoal",
            name="financial_goal_target_date_after_start",
        ),
        migrations.RemoveConstraint(
            model_name="report",
            name="report_period_end_after_start",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="accounts_tr_categor_64aac5_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="accounts_tr_status_9c451f_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_user_id_062bde_idx",
            old_name="accounts_tr_user_id_7b2efb_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_account_91ffc1_idx",
            old_name="accounts_tr_account_3b8440_idx",
        ),
        migrations.AddField(
            model_name="account",
            name="balance_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current balance was last updated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="bank_code",
            field=models.CharField(
                blank=True,
                help_text="Bank code or routing number",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="Whether this account is locked (no transactions allowed)",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the account was last synced with external service",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="reconciled_at",
            field=models.DateTimeField(
                blank=True, help_text="When the account was last reconciled", null=True
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="reconciled_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Last reconciled balance",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="imported_at",
            field=models.DateTimeField(
                blank=True, help_text="When this transaction was imported", null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="imported_source",
            field=models.CharField(
                blank=True,
                help_text="Source of import (e.g., 'CSV', 'Bank API')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_tax_deductible",
            field=models.BooleanField(
                default=False, help_text="Whether this expense is tax deductible"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="location",
            field=models.CharField(
                blank=True, help_text="Transaction location", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Merchant or payee name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="needs_review",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this transaction needs manual review",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="posted_date",
            field=models.DateField(
                blank=True,
                help_text="Date when transaction was posted by bank",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recurrence_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Basic recurrence configuration (frequency, interval, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reference_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Bank or payment reference number",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transfer_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Destination account for transfers",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfer_transactions",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transfer_reference",
            field=models.UUIDField(
                blank=True,
                help_text="Reference to paired transaction in transfer",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("Checking", "Checking"),
                    ("Savings", "Savings"),
                    ("Credit Card", "Credit Card"),
                    ("Cash", "Cash"),
                    ("Investment", "Investment"),
                    ("Loan", "Loan"),
                    ("Other", "Other"),
                ],
                db_index=True,
                default="Cash",
                help_text="Type of account",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.ForeignKey(
                help_text="Account currency",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="core.currency",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="initial_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Starting balance when account was created",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="institution_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional data for bank integrations",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, help_text="Whether this account is active"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_primary",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this is the user's primary account",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Account name (e.g., 'Main Checking', 'Savings')",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.ForeignKey(
                help_text="Owner of the account",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Account associated with the transaction",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="attachments",
            field=models.JSONField(
                blank=True, default=list, help_text="Metadata for attached files"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                help_text="Transaction category",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="core.category",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("1.0"),
                help_text="Exchange rate from original to account currency",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="is_recurring",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is part of a recurring transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="is_transfer",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this is a transfer between accounts",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Transaction description or name",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="original_currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Original currency before conversion",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="original_transactions",
                to="core.currency",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("Pending", "Pending"),
                    ("Canceled", "Canceled"),
                ],
                db_index=True,
                default="Pending",
                help_text="Transaction status",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tags for categorization and filtering",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateField(
                db_index=True,
                default=datetime.date.today,
                help_text="Date when transaction occurred",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("Income", "Income"), ("Expense", "Expense")],
                db_index=True,
                help_text="Income or expense",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "is_active"], name="accounts_user_id_bfbe44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "currency"], name="accounts_user_id_9e8aaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "is_primary"], name="accounts_user_id_9e8fcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "is_active", "account_type"],
                name="idx_accounts_use_is__acc",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["category", "transaction_date"],
                name="transaction_categor_5b779c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["status", "transaction_date"],
                name="transaction_status_b048ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type", "transaction_date"],
                name="transaction_transac_348887_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "status", "transaction_date"],
                name="idx_transact_use_sta_tra",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["account", "status", "transaction_date"],
                name="idx_transact_acc_sta_tra",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="idx_accounts_use_nam"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_balance__gte", Decimal("-1000000000"))),
                name="idx_accounts_cur",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_budget__gt", 0)), name="idx_budgets_tot"
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="idx_budgets_end_sta",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user", "name"),
                name="idx_budgets_use_nam_is_",
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("allocated_amount__gt", 0)), name="idx_budget_c_all"
            ),
        ),
        migrations.AddConstraint(
            model_name="financialgoal",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_amount__gt", 0)), name="idx_financia_tar"
            ),
        ),
        migrations.AddConstraint(
            model_name="financialgoal",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_amount__gte", 0)), name="idx_financia_cur"
            ),
        ),
        migrations.AddConstraint(
            model_name="financialgoal",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_date__gt", models.F("start_date"))),
                name="idx_financia_tar_sta",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gt", models.F("period_start"))),
                name="idx_reports_per_per",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="idx_transact_amo"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)), name="idx_transact_exc"
            ),
        ),
        migrations.AlterModelTable(
            name="transaction",
            table="transactions",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="notes",
        ),
        migrations.DeleteModel(
            name="RecurringTransaction",
        ),
    ]
