# Generated by Django 6.0 on 2025-12-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_remove_recurringtransaction_recurring_t_user_id_839084_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("Checking", "Checking"),
                    ("Savings", "Savings"),
                    ("Credit Card", "Credit Card"),
                    ("Cash", "Cash"),
                    ("Investment", "Investment"),
                    ("Loan", "Loan"),
                    ("Bank", "Bank"),
                    ("Wallet", "Wallet"),
                    ("Other", "Other"),
                ],
                db_index=True,
                default="Cash",
                help_text="Type of account",
                max_length=50,
            ),
        ),
    ]
