# Generated by Django 6.0 on 2025-12-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_account_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("Pending", "Pending"),
                    ("Reconciled", "Reconciled"),
                    ("Canceled", "Canceled"),
                ],
                db_index=True,
                default="Pending",
                help_text="Transaction status",
                max_length=50,
            ),
        ),
    ]
