# Generated by Django 6.0 on 2025-12-23 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0007_budgetcategory_created_at_budgetcategory_updated_at_and_more",
        ),
        ("core", "0004_alter_currency_decimal_places_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="budget_type",
            field=models.CharField(
                choices=[
                    ("Category", "Category Budget"),
                    ("Overall", "Overall Budget"),
                    ("Goal", "Goal-based Budget"),
                ],
                db_index=True,
                default="Category",
                help_text="Type of budget",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="period_type",
            field=models.CharField(
                choices=[
                    ("Monthly", "Monthly"),
                    ("Quarterly", "Quarterly"),
                    ("Yearly", "Yearly"),
                    ("Custom", "Custom Period"),
                ],
                default="Monthly",
                help_text="Budget period type",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="financialgoal",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("Savings", "Savings Goal"),
                    ("Debt", "Debt Repayment"),
                    ("Investment", "Investment Goal"),
                    ("Purchase", "Major Purchase"),
                    ("Other", "Other"),
                ],
                db_index=True,
                default="Savings",
                help_text="Type of financial goal",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="financialgoal",
            name="priority",
            field=models.CharField(
                choices=[
                    ("High", "High Priority"),
                    ("Medium", "Medium Priority"),
                    ("Low", "Low Priority"),
                ],
                db_index=True,
                default="Medium",
                help_text="Priority level of the goal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="format",
            field=models.CharField(
                choices=[
                    ("JSON", "JSON"),
                    ("CSV", "CSV"),
                    ("PDF", "PDF"),
                    ("Excel", "Excel"),
                    ("HTML", "HTML"),
                ],
                default="JSON",
                help_text="Output format of the report",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("Spending by Category", "Spending by Category"),
                    ("Income vs Expense", "Income vs Expense"),
                    ("Net Worth", "Net Worth"),
                    ("Budget vs Actual", "Budget vs Actual"),
                    ("Cash Flow", "Cash Flow"),
                    ("Custom", "Custom Report"),
                ],
                db_index=True,
                help_text="Type of report",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                    ("Cancelled", "Cancelled"),
                ],
                db_index=True,
                default="Pending",
                help_text="Current status of report generation",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="financialgoal",
            index=models.Index(
                fields=["user", "is_achieved"], name="financial_g_user_id_85b6c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialgoal",
            index=models.Index(
                fields=["linked_account"], name="financial_g_linked__1d9857_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="financialgoal",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="idx_financia_use_nam"
            ),
        ),
        migrations.AddConstraint(
            model_name="financialgoal",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_contribution__gte", 0)),
                name="idx_financia_mon",
            ),
        ),
    ]
