# Generated by Django 6.0 on 2025-12-23 13:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_budget_budget_type_alter_budget_period_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialgoal",
            name="progress_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Percentage progress toward goal (0-100)",
                max_digits=10,
            ),
        ),
    ]
