# Generated by Django 6.0 on 2025-12-30 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_financialgoal_progress_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="financial_goal",
            field=models.ForeignKey(
                blank=True,
                help_text="Financial goal associated with this transaction",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="accounts.financialgoal",
            ),
        ),
    ]
