# Generated by Django 6.0 on 2025-12-31 09:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_recurringtransaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringtransaction",
            name="total_generated_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="recurringtransaction",
            name="total_generated_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
