# Generated by Django 6.0 on 2025-12-31 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_recurringtransaction_total_generated_amount_and_more"),
        ("core", "0004_alter_currency_decimal_places_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringtransaction",
            name="currency",
            field=models.ForeignKey(
                default=1,
                help_text="Original currency for this recurring transaction",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recurring_transactions",
                to="core.currency",
            ),
        ),
    ]
